# Setup configuration options.
setup_option_def(SYS_LOG_ENABLE OFF DEFINE "Disables system log for all the components." CONFIG_FILE "sys_log_config")
setup_option_def(SYS_LOG_RUNTIME_UPDATE OFF DEFINE "Enable run time updates of system log levels of all components." CONFIG_FILE "sys_log_config")

if (${SYS_LOG_ENABLE})
    # Default syslog levels for various components.
    setup_option_def(SYS_LOG_LEVEL_DEF "SYS_LOG_INFO|SYS_LOG_WARN|SYS_LOG_ERROR" MACRO "Setup default system log level for undefined components." CONFIG_FILE "sys_log_config")
    setup_option_def(SYS_LOG_LEVEL_MMC "SYS_LOG_INFO|SYS_LOG_WARN|SYS_LOG_ERROR" MACRO "Setup default system log level for MMC." CONFIG_FILE "sys_log_config")
    setup_option_def(SYS_LOG_LEVEL_ENC28J60 "SYS_LOG_INFO|SYS_LOG_WARN|SYS_LOG_ERROR" MACRO "Setup default system log level for ENC28J60." CONFIG_FILE "sys_log_config")
    setup_option_def(SYS_LOG_LEVEL_FATFS "SYS_LOG_INFO|SYS_LOG_WARN|SYS_LOG_ERROR" MACRO "Setup default system log level for FAT file system." CONFIG_FILE "sys_log_config")
    setup_option_def(SYS_LOG_LEVEL_TFTPS "SYS_LOG_INFO|SYS_LOG_WARN|SYS_LOG_ERROR" MACRO "Setup default system log level for TFTPs." CONFIG_FILE "sys_log_config")
    setup_option_def(SYS_LOG_LEVEL_ROUTE "SYS_LOG_INFO|SYS_LOG_WARN|SYS_LOG_ERROR" MACRO "Setup default system log level for NET routes." CONFIG_FILE "sys_log_config")
    setup_option_def(SYS_LOG_LEVEL_ARP "SYS_LOG_INFO|SYS_LOG_WARN|SYS_LOG_ERROR" MACRO "Setup default system log level for ARP." CONFIG_FILE "sys_log_config")
    setup_option_def(SYS_LOG_LEVEL_NET_BUFFER "SYS_LOG_INFO|SYS_LOG_WARN|SYS_LOG_ERROR" MACRO "Setup default system log level for NET buffers." CONFIG_FILE "sys_log_config")
    setup_option_def(SYS_LOG_LEVEL_NET_CONDITION "SYS_LOG_INFO|SYS_LOG_WARN|SYS_LOG_ERROR" MACRO "Setup default system log level for NET condition." CONFIG_FILE "sys_log_config")
    setup_option_def(SYS_LOG_LEVEL_NET_CSUM "SYS_LOG_INFO|SYS_LOG_WARN|SYS_LOG_ERROR" MACRO "Setup default system log level for NET checksum." CONFIG_FILE "sys_log_config")
    setup_option_def(SYS_LOG_LEVEL_NET_DEVICE "SYS_LOG_INFO|SYS_LOG_WARN|SYS_LOG_ERROR" MACRO "Setup default system log level for NET device." CONFIG_FILE "sys_log_config")
    setup_option_def(SYS_LOG_LEVEL_DHCPC "SYS_LOG_INFO|SYS_LOG_WARN|SYS_LOG_ERROR" MACRO "Setup default system log level for DHCP client." CONFIG_FILE "sys_log_config")
    setup_option_def(SYS_LOG_LEVEL_DHCP "SYS_LOG_INFO|SYS_LOG_WARN|SYS_LOG_ERROR" MACRO "Setup default system log level for DHCP." CONFIG_FILE "sys_log_config")
    setup_option_def(SYS_LOG_LEVEL_ICMP "SYS_LOG_INFO|SYS_LOG_WARN|SYS_LOG_ERROR" MACRO "Setup default system log level for ICMP." CONFIG_FILE "sys_log_config")
    setup_option_def(SYS_LOG_LEVEL_IPV4 "SYS_LOG_INFO|SYS_LOG_WARN|SYS_LOG_ERROR" MACRO "Setup default system log level for IPv4." CONFIG_FILE "sys_log_config")
    setup_option_def(SYS_LOG_LEVEL_NET_PROCESS "SYS_LOG_INFO|SYS_LOG_WARN|SYS_LOG_ERROR" MACRO "Setup default system log level for NET process." CONFIG_FILE "sys_log_config")
    setup_option_def(SYS_LOG_LEVEL_TCP "SYS_LOG_INFO|SYS_LOG_WARN|SYS_LOG_ERROR" MACRO "Setup default system log level for TCP stack." CONFIG_FILE "sys_log_config")
    setup_option_def(SYS_LOG_LEVEL_UDP "SYS_LOG_INFO|SYS_LOG_WARN|SYS_LOG_ERROR" MACRO "Setup default system log level for UDP stack." CONFIG_FILE "sys_log_config")
    setup_option_def(SYS_LOG_LEVEL_NET_WORK "SYS_LOG_INFO|SYS_LOG_WARN|SYS_LOG_ERROR" MACRO "Setup default system log level for NET workers." CONFIG_FILE "sys_log_config")
    setup_option_def(SYS_LOG_LEVEL_NET "SYS_LOG_INFO|SYS_LOG_WARN|SYS_LOG_ERROR" MACRO "Setup default system log level for NET stack." CONFIG_FILE "sys_log_config")

    # Setup syslog level definitions.
    set(sys_log_levels SYS_LOG_NONE SYS_LOG_FUNCTION_CALL SYS_LOG_DEBUG SYS_LOG_INFO SYS_LOG_WARN SYS_LOG_ERROR SYS_LOG_ALL)
    setup_option_list_values(SYS_LOG_LEVEL_DEF sys_log_levels "|")
    setup_option_list_values(SYS_LOG_LEVEL_MMC sys_log_levels "|")
    setup_option_list_values(SYS_LOG_LEVEL_ENC28J60 sys_log_levels "|")
    setup_option_list_values(SYS_LOG_LEVEL_FATFS sys_log_levels "|")
    setup_option_list_values(SYS_LOG_LEVEL_TFTPS sys_log_levels "|")
    setup_option_list_values(SYS_LOG_LEVEL_ROUTE sys_log_levels "|")
    setup_option_list_values(SYS_LOG_LEVEL_ARP sys_log_levels "|")
    setup_option_list_values(SYS_LOG_LEVEL_NET_BUFFER sys_log_levels "|")
    setup_option_list_values(SYS_LOG_LEVEL_NET_CONDITION sys_log_levels "|")
    setup_option_list_values(SYS_LOG_LEVEL_NET_CSUM sys_log_levels "|")
    setup_option_list_values(SYS_LOG_LEVEL_NET_DEVICE sys_log_levels "|")
    setup_option_list_values(SYS_LOG_LEVEL_DHCPC sys_log_levels "|")
    setup_option_list_values(SYS_LOG_LEVEL_DHCP sys_log_levels "|")
    setup_option_list_values(SYS_LOG_LEVEL_ICMP sys_log_levels "|")
    setup_option_list_values(SYS_LOG_LEVEL_IPV4 sys_log_levels "|")
    setup_option_list_values(SYS_LOG_LEVEL_NET_PROCESS sys_log_levels "|")
    setup_option_list_values(SYS_LOG_LEVEL_TCP sys_log_levels "|")
    setup_option_list_values(SYS_LOG_LEVEL_UDP sys_log_levels "|")
    setup_option_list_values(SYS_LOG_LEVEL_NET_WORK sys_log_levels "|")
    setup_option_list_values(SYS_LOG_LEVEL_NET sys_log_levels "|")
endif ()


