# Setup configuration options.
setup_option_def(ENC28J60_WDT_TIMEOUT 1000 INT "Maximum number of milliseconds to wait for a TX frame to be sent before resetting a ENC28J60 device.")
setup_option_def(ENC28J60_CLKRDY_TIMEOUT 100 INT "Maximum number of milliseconds to wait for ENC28J60's clock to become ready.")
setup_option_def(ENC28J60_CLKRDY_DELAY 20 INT "Delay between each pool for CLKRDY signal.")
setup_option_def(ENC28J60_CONTINUE_READ ON BOOL "Enables read of consegative frames if available.")
setup_option_def(ENC28J60_INT_POLL ON BOOL "Enables usage of interrupt polling.")
setup_option_def(ENC28J60_REV_ID 0x06 INT "ENC28J60 device revision number.")
setup_option_def(ENC28J60_MAX_BUFFER_SIZE 32 INT "Size of each buffer for ENC28J60 device.")
setup_option_def(ENC28J60_NUM_BUFFERS 32 INT "Number of buffers for ENC28J60 device.")
setup_option_def(ENC28J60_NUM_BUFFER_LISTS 16 INT "Number of buffer lists for ENC28J60 device.")
setup_option_def(ENC28J60_NUM_THR_BUFFER 8 INT "Number of threshold buffers for ENC28J60 device.")
setup_option_def(ENC28J60_NUM_THR_LIST 4 INT "Number of threshold buffer lists for ENC28J60 device.")
setup_option_def(ENC28J60_NUM_ARP 4 INT "Number of ARP entries for ENC28J60 device.")
setup_option_def(ENC28J60_NUM_IPV4_FRAGS 2 INT "Number of IPv4 fragments for ENC28J60 device.")
setup_option_def(ENC28J60_DEFAULT_IP 0xC0A80032 INT "Default IP address for ENC28J60 device if DHCP client is disabled.")
setup_option_def(ENC28J60_DEFAULT_SUBNET 0xFFFFFF00 INT "Default subnet mask for ENC28J60 device if DHCP client is disabled.")