# Setup global configuration options.
setup_option_def(CONFIG_SLEEP ON BOOL "Enable sleep functionality.")
setup_option_def(CONFIG_SEMAPHORE ON BOOL "Enable semaphore functionality.")
setup_option_def(CONFIG_MEMGR OFF BOOL "Enable memory management support.")
setup_option_def(CONFIG_FS OFF BOOL "Enable file system support.")
setup_option_def(CONFIG_NET OFF BOOL "Enable TCP/IP stack support.")
setup_option_def(CONFIG_SERIAL OFF BOOL "Enable serial IO support.")
setup_option_def(CONFIG_I2C OFF BOOL "Enable I2C support.")
setup_option_def(CONFIG_PCF8574 OFF BOOL "Enable I2C based PCF8574 GPIO controller driver.")
setup_option_def(CONFIG_SPI OFF BOOL "Enable SPI support.")
setup_option_def(CONFIG_MMC OFF BOOL "Enable MMC card support.")
setup_option_def(CONFIG_ADC OFF BOOL "Enable ADC support.")
setup_option_def(CONFIG_LCD_AN OFF BOOL "Enable alphanumeric LCD driver.")
setup_option_def(CONFIG_LCD_PCF8574 OFF BOOL "Enable alphanumeric LCD driver over PCF8574 GPIO controller.")
setup_option_def(CONFIG_PPP OFF BOOL "Enable PPP protocol support.")
setup_option_def(CONFIG_ETHERNET OFF BOOL "Enable ethernet support.")
setup_option_def(CONFIG_WEIRD_VIEW OFF BOOL "Enable weird-vview IOT framework.")
setup_option_def(CONFIG_TFTPS OFF BOOL "Enable TFTP server support.")
setup_option_def(CONFIG_BOOTLOAD OFF BOOL "Enable bootloader support.")
