# Setup global configuration options.
setup_option_def(CONFIG_SLEEP ON DEFINE "Enable sleep functionality.")
setup_option_def(CONFIG_SEMAPHORE ON DEFINE "Enable semaphore functionality.")
setup_option_def(CONFIG_MEMGR OFF DEFINE "Enable memory management support.")
setup_option_def(CONFIG_FS OFF DEFINE "Enable file system support.")
setup_option_def(CONFIG_NET OFF DEFINE "Enable TCP/IP stack support.")
setup_option_def(CONFIG_SERIAL OFF DEFINE "Enable serial IO support.")
setup_option_def(CONFIG_I2C OFF DEFINE "Enable I2C support.")
setup_option_def(CONFIG_PCF8574 OFF DEFINE "Enable I2C based PCF8574 GPIO controller driver.")
setup_option_def(CONFIG_SPI OFF DEFINE "Enable SPI support.")
setup_option_def(CONFIG_MMC OFF DEFINE "Enable MMC card support.")
setup_option_def(CONFIG_ADC OFF DEFINE "Enable ADC support.")
setup_option_def(CONFIG_LCD_AN OFF DEFINE "Enable alphanumeric LCD driver.")
setup_option_def(CONFIG_LCD_PCF8574 OFF DEFINE "Enable alphanumeric LCD driver over PCF8574 GPIO controller.")
setup_option_def(CONFIG_PPP OFF DEFINE "Enable PPP protocol support.")
setup_option_def(CONFIG_ETHERNET OFF DEFINE "Enable ethernet support.")
setup_option_def(CONFIG_WEIRD_VIEW OFF DEFINE "Enable weird-vview IOT framework.")
setup_option_def(CONFIG_TFTPS OFF DEFINE "Enable TFTP server support.")
setup_option_def(CONFIG_BOOTLOAD OFF DEFINE "Enable bootloader support.")
